extends: stylelint-config-standard
rules:
  declaration-block-single-line-max-declarations: null
  font-family-name-quotes: null
  no-descending-specificity: null
  function-url-quotes: null
  property-no-unknown: null
  selector-id-pattern: null
  selector-class-pattern: null
  media-feature-name-no-unknown: null
