apiVersion: apps/v1
kind: Deployment
metadata:
  name: putout-editor
  namespace: putout-editor
  labels:
    app: putout-editor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: putout-editor
  template:
    metadata:
      labels:
        app: putout-editor
    spec:
      containers:
        - name: putout-editor
          image: ghcr.io/coderaiser/putout-editor
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
