apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: putout-editor
  namespace: putout-editor
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - putout-editor.cloudcmd.io
      secretName: putout-editor-tls
  rules:
    - host: putout-editor.cloudcmd.io