name: k8s-lint
permissions:
  contents: write
on:
  pull_request:
    paths:
      - deploy/k8s/**
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - name: Install
        run: |
          bun i -g palabra
          palabra i kubeconform
      - name: kubeconform
        run: kubeconform -summary -strict deploy/k8s/